print("Zadatak 1.4.1")
print("Unesite broj radnih sati:")
hours = float(input())
print("Unesite plaću po radnom satu:")
payPerHour = float(input())
pay = float(hours * payPerHour)
print("Radni sati:", hours)
print("eura/h:", payPerHour)
print("Ukupno:", pay) 